### ISSUE TITLE
Correct purchase flow to handle Cash payments for consumables?

### ISSUE THREAD

**Issue by rknoesel** [moisoni97/google-inapp-billing#16]
Thanks for creating this wrapper, it looks very useful.
One question I have, is how can I use this library to correctly handle those new Cash payments that are now happening in Indonesia, Malaysia, etc?  In those cases the user makes the purchase, then later goes to a convenience store to make the actual payment.  Google recommends using the PurchaseToken to store information about a consumable on our own servers, which can then be granted later when the cash payment is made.
It would be super helpful if you could add some sample code that correctly handles this type of situation.
Thanks!

**Comment by moisoni97** [comment]
Actually, I don't know. To avoid this problem for `non-consumable` products, user entitlement should be granted in `onPurchaseAcknowledged` callback, but for `consumable` products it's more complicated and I guess you should use server-side verification. I don't think it's possible for me to do something within the library to help with this.

**Comment by moisoni97** [comment]
Yes, I already need to make some changes to the code and definitely will do this too.
Thanks for the suggestion.

Does `onPurchaseConsumed` get called if `CONSUME_ERROR` is called?

**Comment by moisoni97** [comment]
Ok, I looked at the code and `onPurchaseConsumed` is not called if `CONSUME_ERROR` is called so you can make a workaround without involving a server verification.

You should grant user entitlement in `onPurchaseConsumed` and if everything goes as expected (without pending purchase) the user will have its purchase instantly, but if the purchase is pending, `CONSUME_ERROR` is called and there you should inform the user that the payment isn't completed yet and it may take a while until it's done and to come back later to receive the product. In this case, after the purchase is completed and the user reopens the app, `onPurchaseConsumed` will be called again. This will make more sense when I'll add `CONSUME_WARNING` because `CONSUME_ERROR` may be called for a different issue other than a pending transaction.

**Comment by rknoesel** [comment]
Perfect!  Yes, currently I'm able to work around this with CONSUME_ERROR, and everything works as it should.

Thanks!

**Comment by rknoesel** [comment]
Thanks!
