### ISSUE TITLE
Caching purchases

### ISSUE THREAD

**Issue by OneDevUA** [moisoni97/google-inapp-billing#28]
I am using the latest version of the library. Everything works as it should. But there is one thing: when I turn off the Internet connection, there must be a connection error. But the library takes purchases from somewhere. I understand that from the cache. How can I turn off the caching of purchases?

**Comment by moisoni97** [comment]
You can't turn off caching because it's handled by Google API, but you can make a workaround.
The `onPurchasedProductsFetched` listener is called using data from that specific cache, so in your case, you should implement a network check here, and if there is no internet available just skip the steps you are doing when the internet is available.
