### ISSUE TITLE
Did this library test in real app?

### ISSUE THREAD

**Issue by JVeverGiveUp** [moisoni97/google-inapp-billing#3]
Dear moison97,
Sorry for my question, I'm new to Google IAP. I recently just include other IAP library. And all my orders are auto refund after 3 days. So I want to know if you already used this library in your app?
Thank you very much (Sorry that Github does not have message function to me to ask directly)

**Comment by moisoni97** [comment]
Hi,
Actually, I haven't tested the library in production yet because I'm still working on my app update, but in a week or so should be ready to publish and I can tell you the results then.

While developing the library I have tested with `test purchases` to ensure everything works.

Specific to your problem, refunding after 3 days indicates that may be a problem with `acknowledgment` because Google said that purchases that aren't acknowledged will be refunded to users in 3 days. Another possibility is that you get a refund on your own `test purchases` which I believe is normal.

If you are using this library don't forget to call `.autoAcknowledge()` to acknowledge the purchase and then in `onPurchaseAcknowledged` callback you can check if the acknowledgment was successful or not.

**Comment by JVeverGiveUp** [comment]
Thank you very much for your respond. I really appreciate that! It because of lack acknowledgePurchase.
Thank you again!
Dat

**Comment by moisoni97** [comment]
Hi,
I've added new features and improvements to the library.
Check out the latest version of the library: `implementation 'com.github.moisoni97:google-inapp-billing:1.0.2'` and also read again the `README.md` file because I have updated the documentation.

If using this library correctly Google refunds shouldn't happen.
