### ISSUE TITLE
Upgrade to Billing 5.0

### ISSUE THREAD

**Issue by yahlamobile** [moisoni97/google-inapp-billing#37]
Hi, do you have any plans to update this to billing 5.0

Thanks

**Comment by mert-karadeniz** [comment]
Upgraded to billing v5.0 :)

**Comment by moisoni97** [comment]
Tomorrow I'll try to update the ReadMe and publish the latest version on Jitpack.

**Comment by yahlamobile** [comment]
Nice, i appreciate your hard work..Thank you

**Comment by yahlamobile** [comment]
Hi again, can you make it into a release build on JitPack...Latest release is still 1.0.8...thanks

**Comment by moisoni97** [comment]
Hi,
I made the release yesternight, but despite the fact that everything works, JitPack just throw a build error, because they always change something in the configuration so I had no choice but to delete the release.
It was to late in the evening to figure it out what's wrong. I'll try to make the release tonight...

**Comment by moisoni97** [comment]
Done!
