### ISSUE TITLE
Can we get SKU Detail after app un-installed?

### ISSUE THREAD

**Issue by GauravCreed** [moisoni97/google-inapp-billing#6]
Hi @moisoni97 

Issue : After purchase product i just uninstall application, then re-install app on other device, 
How can i get purchased SKU detail on other device also.

Thanks.

**Comment by moisoni97** [comment]
Hi,
Purchases are linked to your `Google account` so you need to be logged in on the other device with the same account. After successfully logging in, `onPurchasedProductsFetched` should be called.

If you are interested to get other SKU details returned by the `Google Billing API` like price or purchase token, see issue #1

**Comment by GauravCreed** [comment]
Hi @moisoni97 

Yes. you are right, we have sign in same account with other device.
I think we can get all purchased item from **queryPurchasesAsync**. am i right?


Thanks.

**Comment by moisoni97** [comment]
I can't guarantee `queryPurchasesAsync` will work every time because this method uses a cache of the Google Play Store app without initiating a network request. 
Google recommends caching purchase details on your server.

Alternatively, you can use `isPurchased(SkuInfo skuInfo)` method (see sample app for example) provided by the library to check for purchased products, but again this method is dependent on `queryPurchasesAsync`.

In the worst case, the library won't detect the purchased products (because of how the `Google Billing API` works) and the user will be prompted to buy the product again.
When trying to buy again an already owned product, `onBillingError` callback will be triggered with `ErrorType: ITEM_ALREADY_OWNED` and purchased products can be restored here.
