### ISSUE TITLE
Error retriving information from server

### ISSUE THREAD

**Issue by AnshumanHexabrain** [moisoni97/google-inapp-billing#7]
Hello,
I have added your library in my application but while subscribe I am getting an error like `DF-DFERH-01` 

I have also tried to clear data/cache in playstore as well

please let me know if you have an any idea about that 
![device-2021-07-28-085646](https://user-images.githubusercontent.com/72792585/127260767-a9542fc2-e58a-484b-8b88-9f302dcaf079.png)

**Comment by moisoni97** [comment]
This seems like a connectivity issue with Google servers, not necessarily a problem with the library.
Can I see your code? Also in the `logcat` search for `BillingConnector` and show me what it prints.

**Comment by AnshumanHexabrain** [comment]
![image](https://user-images.githubusercontent.com/72792585/127428108-d5cb772f-f13e-44a7-b8db-8a4cd76d1e1f.png)
![image](https://user-images.githubusercontent.com/72792585/127428137-faea8694-816f-4424-aeed-648fac33cf9f.png)
![image](https://user-images.githubusercontent.com/72792585/127428207-c13d7111-b7a1-4930-838e-bc06a60e8a71.png)



Here is my code

**Comment by AnshumanHexabrain** [comment]
and I here is my log 
![image](https://user-images.githubusercontent.com/72792585/127428243-8f314df0-7a08-4a50-bb60-6f39e7f01586.png)

**Comment by moisoni97** [comment]
It's not a problem with the library itself because it's working correctly and throw the `SERVICE_UNAVAILABLE` error.
This [stackoverflow question](https://stackoverflow.com/questions/15889480/iabresult-billing-service-unavailable-on-device-response-3billing-unavailab) may be useful for you to diagnose the problem.

Have you added the permission `<uses-permission android:name="com.android.vending.BILLING" />` in the manifest?
